# read folder name from tag `folder`
folder.name=#folder
# read api name from tag `api.name`
api.name=#api.name

api.status[#obsolete]=obsolete

field.schema.permit.null=@jakarta.validation.constraints.NotNull