spring.profiles.active=dev
spring.application.name=lan-api-starter
server.port=5488

# database config
spring.datasource.url=jdbc:mysql://43.139.167.10:3306/ace?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-plus Config
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
mybatis-plus.type-aliases-package=com.marvel.lan.infrastructure.persistence.po
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.logic-delete-field=deletedAt
mybatis-plus.global-config.db-config.logic-not-delete-value=null
mybatis-plus.global-config.db-config.logic-delete-value=NOW()